<?xml version="1.0" encoding="UTF-8"?>
                                     <qmt>
                                     <project>
                                     <uid>{2be0e528-75f5-43de-9596-15de14988930}</uid>
                                     <root-package>
                                     <instance>
                                     <MPackage>
                                     <base-MObject>
                                     <MObject>
                                     <base-MElement>
                                     <MElement>
                                     <uid>{ec3a8846-3dab-4c1d-81c2-5fd0142ffaff}</uid>
                                     </MElement>
                                     </base-MElement>
                                     <name>ui_newwindow.h</name>
                                     <children>
                                     <handles>
                                     <handles>
                                     <qlist>
                                     <item>
                                     <handle>
                                     <uid>{b71b7222-f424-4845-8345-47e270cec7d9}</uid>
                                     <target>
                                     <instance type="MCanvasDiagram">
        <MCanvasDiagram>
        <base-MDiagram>
        <MDiagram>
        <base-MObject>
        <MObject>
        <base-MElement>
        <MElement>
        <uid>{b71b7222-f424-4845-8345-47e270cec7d9}</uid>
        </MElement>
        </base-MElement>
        <name>ui_newwindow.h</name>
        </MObject>
        </base-MObject>
        </MDiagram>
        </base-MDiagram>
        </MCanvasDiagram>
        </instance>
        </target>
        </handle>
        </item>
        </qlist>
        </handles>
        </handles>
        </children>
        </MObject>
        </base-MObject>
        </MPackage>
        </instance>
        </root-package>
        </project>
        </qmt>
